name: angbug
dependencies:
  # angular2: 2.0.0-beta.18
  angular2: 2.0.0-beta.21
  browser: ^0.10.0
  polymer: "1.0.0-rc.18"
  polymer_elements: "1.0.0-rc.8"
  web_components: ^0.12.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- polymer:
    entry_points: web/index.html
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
